### ISSUE TITLE
Unable to get this working.

### ISSUE THREAD

**Issue by pms1969** [victorcoder/docker-dkron#3]
I might be just running the wrong OS (win10) but I don't seem to be able to get this working.

I run the command ` docker run --name some-dkron -d dkron/dkron agent -server` and it fails, 
so I run `docker run -ti dkron/dkron agent -server` and the output is as such:

```
INFO[2016-11-03T14:40:32Z] agent: Dkron agent starting                   node=dbb9a3f39ecd
INFO[2016-11-03T14:40:32Z] agent: joining: [] replay: true               node=dbb9a3f39ecd
FATA[2016-11-03T14:40:32Z] store: Store backend not reachable            error=client: etcd cluster is unavailable or misconfigured node=dbb9a3f39ecd
```

I don't see any installation related to etcd, so was guessing I'm either missing something (Like the appropriate docker container already running) or I'm just being thick.

Any help appreciated.

**Comment by vcastellm** [comment]
@pms1969 yes, dkron needs a storage backend to work, it can work with three different storage backends, etcd, consul or zookeeper.

For a quick start you can take inspiration from the project compose file in https://github.com/victorcoder/dkron/blob/master/docker-compose.yml
