### ISSUE TITLE
Docker version tags

### ISSUE THREAD

**Issue by vincer** [victorcoder/docker-dkron#4]
It would be useful for deployment reasons to start tagging images in Docker Hub.

Each release gets its own tag (0.9.1 release would get a "0.9.1" tag)
Every major and minor version would get a version tag in the standard "docker" way. (tag "0.9" would point to the latest 0.9.x release)

**Comment by vcastellm** [comment]
Duplicate of https://github.com/victorcoder/dkron/issues/211
